# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        appBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        default:
            entity:
                class: AppBundle:User
                property: email

    firewalls:
        register:
            pattern: ^/api/register
            anonymous: ~
            stateless: true
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: ~
            form_login:
                check_path:               /api/login_check
                require_previous_session: false
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: true
            provider: default
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_ANONYMOUSLY }
